# tomcat-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: makaan:1.0.0-15
spec:
  replicas: 2
  selector:
    matchLabels:
      app: makaan:1.0.0-15
  template:
    metadata:
      labels:
        app: makaan:1.0.0-15
    spec:
      containers:
      - name: makaan:1.0.0-15
        image: krishnamsg/makaan:1.0.0-15
        ports:
        - containerPort: 8080
