# tomcat-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: makaan-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: makaan
  template:
    metadata:
      labels:
        app: makaan
    spec:
      containers:
      - name: ttomcat-container
        image: krishnamsg/makaan:1.0.0-2
        ports:
        - containerPort: 8080