# tomcat-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: complete-production-makaan-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: complete-production-makaan-pipeline
  template:
    metadata:
      labels:
        app: complete-production-makaan-app
    spec:
      containers:
      - name: complete-production-e2e-makaan-pipeline:1.0.0-22
        image: krishnamsg/complete-production-e2e-makaan-pipeline:1.0.0-22
        ports:
        - containerPort: 8080
