# tomcat-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: makaan-kubernetes-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: makaan-kubernetes-pipeline
  template:
    metadata:
      labels:
        app: makaan-application-app
    spec:
      containers:
      - name: makaan-kubernetes-pipeline
        image: krishnamsg/makaan:1.0.0-14
        ports:
        - containerPort: 8080
