# tomcat-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: makaan:1.0.0-12
spec:
  replicas: 2
  selector:
    matchLabels:
      app: makaan:1.0.0-12
  template:
    metadata:
      labels:
        app: makaan:1.0.0-12
    spec:
      containers:
      - name: ttomcat-container
        image: krishnamsg/makaan:1.0.0-12
        ports:
        - containerPort: 8080