# tomcat-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: makaan-service
spec:
  selector:
    app: makaan
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort