# tomcat-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: complete-production-makaan-deployment
spec:
  selector:
    app: tomcat-makaan
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
